// Permanent Stripe seeder for ThreeFold Originals — idempotent & resumable.
//
//   node scripts/stripe-seed.mjs            # PLAN: inspect state, print CREATE/COMPLETE/SKIP, change nothing
//   STRIPE_SECRET_KEY='sk_...' node scripts/stripe-seed.mjs            # PLAN with live Stripe check + refresh price map
//   STRIPE_SECRET_KEY='sk_...' node scripts/stripe-seed.mjs --create   # apply missing pieces only
//
// SOURCE OF TRUTH: scripts/products.csv  (columns: slug,name,collection,price_usd)
// Future drops = add rows to that CSV and re-run the same command.
//
// SECURITY: reads STRIPE_SECRET_KEY from the environment only. Never hard-code the key,
// never write it to a file. This script and products.csv are committed (no secrets in
// either); stripe-links.json (generated output) stays git-ignored.
//
// Per product it ensures: a Product (tax_code txcd_30011000 general clothing,
// metadata.slug + metadata.collection), a one-time USD Price at the CSV amount, and a
// Payment Link (US shipping address, adjustable quantity, automatic_tax ON, required
// "Size" dropdown S/M/L/XL/2XL, metadata.slug). It also (re)writes the COMMITTABLE map
// functions/api/price-map.js (slug -> { name, price_id }) used by the cart checkout.
//
// RESUMABLE / IDEMPOTENT — safe to run repeatedly:
//   slug already in stripe-links.json -> SKIP; product+link exist -> SKIP (URL recorded);
//   product exists but no link -> COMPLETE; nothing exists -> CREATE.
// Never edits/deletes existing Stripe objects. Per-row failures are caught and reported.

import Stripe from "stripe";
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";

const TAX_CODE = "txcd_30011000";
const CURRENCY = "usd";
const SIZES = ["S", "M", "L", "XL", "2XL"];
const CSV_FILE = "scripts/products.csv";
const LINKS_FILE = "scripts/stripe-links.json";
const PRICEMAP_FILE = "functions/api/price-map.js";

const doCreate = process.argv.includes("--create");

function parseCsv(text) {
  const rows = [];
  for (const raw of text.split(/\r?\n/)) {
    if (!raw.trim()) continue;
    const cells = []; let cur = "", q = false;
    for (let i = 0; i < raw.length; i++) {
      const c = raw[i];
      if (q) { if (c === '"' && raw[i + 1] === '"') { cur += '"'; i++; } else if (c === '"') q = false; else cur += c; }
      else if (c === '"') q = true;
      else if (c === ",") { cells.push(cur); cur = ""; }
      else cur += c;
    }
    cells.push(cur); rows.push(cells.map((s) => s.trim()));
  }
  const header = rows.shift();
  return rows.map((r) => Object.fromEntries(header.map((h, i) => [h, r[i] ?? ""])));
}

function loadProducts() {
  if (!existsSync(CSV_FILE)) { console.error(`ERROR: ${CSV_FILE} not found.`); process.exit(1); }
  const seen = new Set();
  return parseCsv(readFileSync(CSV_FILE, "utf8")).map((r, idx) => {
    if (!r.slug) { console.error(`ERROR: row ${idx + 2} has no slug.`); process.exit(1); }
    if (seen.has(r.slug)) { console.error(`ERROR: duplicate slug "${r.slug}".`); process.exit(1); }
    seen.add(r.slug);
    const cents = Math.round(parseFloat(r.price_usd) * 100);
    if (!Number.isFinite(cents) || cents <= 0) { console.error(`ERROR: bad price for "${r.slug}".`); process.exit(1); }
    return { slug: r.slug, name: r.name, collection: r.collection, cents };
  });
}

function loadLinks() {
  if (!existsSync(LINKS_FILE)) return {};
  try { return JSON.parse(readFileSync(LINKS_FILE, "utf8")); } catch { return {}; }
}
const saveLinks = (l) => writeFileSync(LINKS_FILE, JSON.stringify(l, null, 2) + "\n");
const money = (c) => `$${(c / 100).toFixed(2)} ${CURRENCY.toUpperCase()}`;

function writePriceMap(map) {
  mkdirSync("functions/api", { recursive: true });
  const body = Object.entries(map).map(([slug, v]) =>
    `  ${JSON.stringify(slug)}: { "name": ${JSON.stringify(v.name)}, "unit_cents": ${Number.isInteger(v.unit_cents) && v.unit_cents > 0 ? v.unit_cents : 0}, "price": ${JSON.stringify(v.price || "")} },`
  ).join("\n");
  writeFileSync(PRICEMAP_FILE,
`// slug -> { name, unit_cents, price }  (unit price in cents from products.csv + Stripe Price ID).
// Regenerated by scripts/stripe-seed.mjs. Committable — contains no secrets.
// unit_cents is what the SERVER charges (functions/api/_lib.js validateCart); 0 = not priced,
// which the server rejects loudly. Empty price = not seeded yet.
export default {
${body}
};
`);
}
function loadExistingPriceMap() {
  // best-effort: keep names/prices we already committed if Stripe lookup is skipped
  if (!existsSync(PRICEMAP_FILE)) return {};
  try {
    const txt = readFileSync(PRICEMAP_FILE, "utf8");
    const m = {};
    const re = /"([^"]+)":\s*\{\s*"name":\s*("(?:[^"\\]|\\.)*")\s*,\s*"price":\s*("(?:[^"\\]|\\.)*")\s*\}/g;
    let x; while ((x = re.exec(txt))) m[x[1]] = { name: JSON.parse(x[2]), price: JSON.parse(x[3]) };
    return m;
  } catch { return {}; }
}

async function findProduct(stripe, slug) {
  try { const r = await stripe.products.search({ query: `metadata['slug']:'${slug}'`, limit: 1 }); if (r.data[0]) return r.data[0]; } catch {}
  for await (const p of stripe.products.list({ limit: 100 })) if (p.metadata && p.metadata.slug === slug) return p;
  return null;
}
async function findActivePrice(stripe, productId, cents) {
  for await (const pr of stripe.prices.list({ product: productId, active: true, limit: 100 }))
    if (pr.unit_amount === cents && pr.currency === CURRENCY && !pr.recurring) return pr;
  return null;
}
async function findPaymentLink(stripe, slug) {
  for await (const pl of stripe.paymentLinks.list({ limit: 100 })) if (pl.active && pl.metadata && pl.metadata.slug === slug) return pl;
  return null;
}

const products = loadProducts();
const links = loadLinks();
const priceMap = loadExistingPriceMap();
products.forEach((p) => { priceMap[p.slug] = { name: p.name, unit_cents: p.cents, price: (priceMap[p.slug] && priceMap[p.slug].price) || "" }; });

const key = process.env.STRIPE_SECRET_KEY;
const stripe = key ? new Stripe(key) : null;

console.log(`\n${doCreate ? "CREATE" : "PLAN (dry run)"} — ${products.length} rows from ${CSV_FILE}` + (stripe ? "" : "  [no key: Stripe not checked]"));
console.log("  #  | action    | Product                     | Price       | slug");
console.log("  ---+-----------+-----------------------------+-------------+--------------------------");

const decisions = [];
for (let i = 0; i < products.length; i++) {
  const p = products[i]; let action = "CREATE?", why = "no key — unchecked", product = null, price = null, link = null;
  const known = links[p.slug] && String(links[p.slug]).startsWith("http");
  if (stripe) {
    // ALWAYS resolve product+price so price-map.js is populated for every row — even SKIP rows.
    product = await findProduct(stripe, p.slug);
    if (product) {
      price = await findActivePrice(stripe, product.id, p.cents);
      if (price) priceMap[p.slug].price = price.id;
      link = await findPaymentLink(stripe, p.slug);
    }
    if (link) { links[p.slug] = link.url; action = "SKIP"; why = "product + link exist"; }
    else if (known) { action = "SKIP"; why = "in stripe-links.json"; }
    else if (product) { action = "COMPLETE"; why = "product exists, missing link"; }
    else { action = "CREATE"; why = "no product yet"; }
  } else if (known) { action = "SKIP"; why = "in stripe-links.json"; }
  decisions.push({ p, action, product, price, link });
  console.log("  " + String(i + 1).padStart(2) + " | " + action.padEnd(9) + " | " + p.name.padEnd(27) + " | " + money(p.cents).padEnd(11) + " | " + p.slug + "   (" + why + ")");
}

if (stripe) writePriceMap(priceMap); // refresh committable map from whatever we could resolve

if (!doCreate) {
  console.log(`\nDry run — nothing created. price-map.js ${stripe ? "refreshed" : "unchanged"}. Re-run with --create (key set) to apply.\n`);
  process.exit(0);
}
if (!stripe) { console.error("\nERROR: --create requires STRIPE_SECRET_KEY. Nothing created.\n"); process.exit(1); }

let created = 0, completed = 0, skipped = 0, failed = 0;
for (const d of decisions) {
  const p = d.p;
  if (d.action === "SKIP") { skipped++; continue; }
  console.log(`\n[${p.slug}] ${d.action}…`);
  try {
    let product = d.product || (await findProduct(stripe, p.slug));
    if (!product) { product = await stripe.products.create({ name: p.name, tax_code: TAX_CODE, metadata: { slug: p.slug, collection: p.collection } }); console.log(`  product   ${product.id} (created)`); }
    else console.log(`  product   ${product.id} (exists)`);
    let existing = d.link || (await findPaymentLink(stripe, p.slug));
    let price = d.price || (await findActivePrice(stripe, product.id, p.cents));
    if (!price) { price = await stripe.prices.create({ product: product.id, currency: CURRENCY, unit_amount: p.cents }); console.log(`  price     ${price.id} (created)`); }
    else console.log(`  price     ${price.id} (exists)`);
    priceMap[p.slug].price = price.id;
    if (!existing) {
      existing = await stripe.paymentLinks.create({
        line_items: [{ price: price.id, quantity: 1, adjustable_quantity: { enabled: true, minimum: 1 } }],
        shipping_address_collection: { allowed_countries: ["US"] },
        automatic_tax: { enabled: true },
        custom_fields: [{ key: "size", label: { type: "custom", custom: "Size" }, type: "dropdown", optional: false, dropdown: { options: SIZES.map((s) => ({ label: s, value: s.toLowerCase() })) } }],
        metadata: { slug: p.slug, collection: p.collection },
      });
      console.log(`  link      ${existing.url} (created)`);
      if (d.action === "COMPLETE") completed++; else created++;
    } else { console.log(`  link      ${existing.url} (exists)`); skipped++; }
    links[p.slug] = existing.url;
    saveLinks(links); writePriceMap(priceMap);
  } catch (err) { failed++; console.error(`  ✗ ${p.slug}: ${err && err.message ? err.message : err}`); }
}
saveLinks(links); writePriceMap(priceMap);
console.log(`\n${failed ? "⚠️ " : "✅ "}Done. created=${created} completed=${completed} skipped=${skipped} failed=${failed}`);
console.log(`stripe-links.json: ${Object.keys(links).length}/${products.length} URLs. price-map.js refreshed (commit it).`);
if (failed) { console.log(`Some rows failed (often automatic_tax = Stripe Tax not enabled — see SETUP-STRIPE.md). Re-run to finish the rest.`); process.exit(1); }
